management:
  endpoints:
    web:
      exposure:
        include: info, prometheus
      base-path:
      path-mapping:
        info: /actuator/info
        prometheus: /metrics

server:
  port: 8000

spring:
  datasource:
    url: "jdbc:postgresql://postgres:5432/postgres?currentSchema=public"
    username: "postgres"
    password: "123"
    jpa:
      show-sql: true

grpc:
  server:
    port: 9090
    permit-keep-alive-without-calls: true
