management:
  endpoints:
    web:
      exposure:
        include: info, prometheus, health
      base-path:
      path-mapping:
        info: /actuator/info
        prometheus: /metrics
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true


spring:
  data:
    mongodb:
      uri: mongodb://${MDB_USERNAME}:${MDB_PASSWORD}@${MDB_HOST}:${MDB_PORT}/${MDB_NAME}?authSource=admin
#      host: ${MDB_HOST}
#      port: ${MDB_PORT}
#      database: ${MDB_NAME}
#      username: ${MDB_USERNAME}
#      password: ${MDB_PASSWORD}
#      authentication-database: admin

landscape:
  url: http://${LANDSCAPE_HOST}:${LANDSCAPE_PORT}

server:
  port: 80

grpc:
  server:
    port: 90
    permit-keep-alive-without-calls: true
