apiVersion: apps/v1
kind: Deployment
metadata:
  name: handyman-deployment
  labels:
    app: handyman
spec:
  replicas: 2
  selector:
    matchLabels:
      app: handyman
  template:
    metadata:
      labels:
        app: handyman
    spec:
      containers:
        - name: handyman-service
          image: bluebasooo/tacademy:handyman-service
          ports:
          - containerPort: 80
          - containerPort: 9000

---

apiVersion: v1
kind: Service
metadata:
  name: handyman-out
spec:
  type: NodePort
  selector:
    app: handyman
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010

---

apiVersion: v1
kind: Service
metadata:
  name: handyman-service
spec:
  selector:
    app: handyman
  ports:
    - name: grpc
      protocol: TCP
      port: 9000
      targetPort: 9000