apiVersion: apps/v1
kind: Deployment
metadata:
  name: landscape-deployment
  labels:
    app: landscape
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landscape
  template:
      metadata:
        labels:
          app: landscape
      spec:
        containers:
          - name: landscape-service
            image: bluebasooo/tacademy:landscape-service
            ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: landscape-out
spec:
  type: NodePort
  selector:
    app: landscape
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30011
