apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-deployment
  labels:
    app: rancher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rancher
  template:
    metadata:
      labels:
        app: rancher
    spec:
      containers:
        - name: rancher-service
          image: bluebasooo/tacademy:rancher-service
          ports:
          - containerPort: 8000
          - containerPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: rancher-out
spec:
  type: NodePort
  selector:
    app: rancher
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30012

---

apiVersion: v1
kind: Service
metadata:
  name: rancher-service
spec:
  selector:
    app: rancher
  ports:
    - name: grpc
      protocol: TCP
      port: 9090
      targetPort: 9090
